package ch.akros.marketplace.constants;

public enum IFieldTypeDefinition {
	EMPTY, NUMBER, TEXT_SINGLE_LINE, TEXT_MULTI_LINE, ADDRESS, CHOOSE_SINGLE_OPTION, CHOOSE_MULTI_OPTION, BOOLEAN,
	EMAIL, PHONE_NUMBER, PICTURE, DATE, PRICE;
}
